"use client";

import { useState } from "react";

export function ProjectSummary({ summary, disabled, onConfirm, onCorrect }: { summary: string; disabled: boolean; onConfirm: () => void; onCorrect: (message: string) => Promise<void> | void }) {
  const [editing, setEditing] = useState(false);
  const [correction, setCorrection] = useState("");
  return <section className="rounded-2xl border border-border-default bg-surface p-5 sm:p-6" aria-labelledby="project-summary-title"><p className="text-xs font-semibold tracking-[0.2px] text-accent">RESUMEN DEL PROYECTO</p><h2 id="project-summary-title" className="mt-2 text-xl font-bold tracking-[-0.4px] text-text-primary">Esto es lo que he entendido</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-text-primary">{summary}</p>
    {editing ? <form className="mt-5 flex flex-col gap-2" onSubmit={(event) => { event.preventDefault(); if (correction.trim()) void onCorrect(correction.trim()); }}><label htmlFor="summary-correction" className="text-sm font-semibold text-text-primary">¿Qué debo corregir?</label><textarea id="summary-correction" rows={3} maxLength={4_000} value={correction} onChange={(event) => setCorrection(event.target.value)} placeholder="Por ejemplo: no necesitamos pagos; el lanzamiento sería en septiembre." className="resize-none rounded-[14px] border border-border-default bg-surface-raised px-3.5 py-3 text-sm text-text-primary placeholder:text-text-secondary" /><div className="flex gap-2"><button type="submit" disabled={disabled || !correction.trim()} className="inline-flex h-11 items-center justify-center rounded-[14px] bg-action px-5 text-sm font-semibold text-action-fg disabled:opacity-60">Actualizar</button><button type="button" onClick={() => setEditing(false)} className="inline-flex h-11 items-center justify-center rounded-[14px] px-4 text-sm font-semibold text-text-secondary">Cancelar</button></div></form> : <div className="mt-5 flex flex-col gap-2 sm:flex-row"><button type="button" disabled={disabled} onClick={onConfirm} className="inline-flex h-11 flex-1 items-center justify-center rounded-[14px] bg-action px-5 text-sm font-semibold text-action-fg disabled:opacity-60">Confirmar</button><button type="button" disabled={disabled} onClick={() => setEditing(true)} className="inline-flex h-11 flex-1 items-center justify-center rounded-[14px] border border-border-strong bg-surface px-5 text-sm font-semibold text-text-primary hover:bg-bg-brand-soft disabled:opacity-60">Editar / corregir</button></div>}
  </section>;
}
